### ISSUE TITLE
Login not working 

### ISSUE THREAD

**Issue by AliaksandrHudnyi** [paralect/ship#27]
On local environment
1. OPen signin page
1. Enter Valid Email
1. Enter Valid Password
1. Press Let me in

**Issue: Internal Server Error** 
```
web_1      |   <-- GET /?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YTlhYjA0ZGNjNGIxYTAwMWMyYmUyYmYiLCJpYXQiOjE1MjAwODcxNzAsImF1ZCI6ImFwaSIsImlzcyI6ImFwaSJ9.PKVSQ5jRQgY4nWOQFxZREVQdzwKPkiAF-3HyUZPtYcU
web_1      |   xxx GET /?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YTlhYjA0ZGNjNGIxYTAwMWMyYmUyYmYiLCJpYXQiOjE1MjAwODcxNzAsImF1ZCI6ImFwaSIsImlzcyI6ImFwaSJ9.PKVSQ5jRQgY4nWOQFxZREVQdzwKPkiAF-3HyUZPtYcU 500 0ms -
web_1      | 
web_1      |   Error: session store is unavailable
web_1      |       at /app/node_modules/koa-generic-session/lib/session.js:75:15
web_1      |       at Generator.next (<anonymous>)
web_1      |       at step (/app/node_modules/koa-generic-session/lib/session.js:3:191)
web_1      |       at /app/node_modules/koa-generic-session/lib/session.js:3:437
web_1      |       at new Promise (<anonymous>)
web_1      |       at /app/node_modules/koa-generic-session/lib/session.js:3:99
web_1      |       at getSession (/app/node_modules/koa-generic-session/lib/session.js:123:19)
web_1      |       at /app/node_modules/koa-generic-session/lib/session.js:218:28
web_1      |       at Generator.next (<anonymous>)
web_1      |       at step (/app/node_modules/koa-generic-session/lib/session.js:3:191)
web_1      |       at /app/node_modules/koa-generic-session/lib/session.js:3:437
web_1      |       at new Promise (<anonymous>)
web_1      |       at /app/node_modules/koa-generic-session/lib/session.js:3:99
web_1      |       at session (/app/node_modules/koa-generic-session/lib/session.js:281:20)
web_1      |       at dispatch (/app/node_modules/koa-compose/index.js:42:32)
web_1      |       at next (/app/node_modules/koa-compose/index.js:43:18)
web_1      | 
```

**Comment by ezhivitsa** [comment]
@AliaksandrHudnyi Fixed, please test.

**Comment by AliaksandrHudnyi** [comment]
It looks like at localhost fix does not work.
I also tries admin hack to change at Mongo 
from "isEmailVerified" : false, to "isEmailVerified" : true,

Please check, Thanks
```
api_1      |   <-- POST /account/signin
api_1      | error:  errors=[email=Please verify your email to sign in]
api_1      |   --> POST /account/signin 400 142ms 60b
api_1      |   <-- POST /account/signin
api_1      | error:  errors=[email=Please verify your email to sign in]
api_1      |   --> POST /account/signin 400 136ms 60b
api_1      |   <-- POST /account/signin
api_1      | error:  errors=[email=Please verify your email to sign in]
api_1      |   --> POST /account/signin 400 138ms 60b
api_1      |   <-- POST /account/signin
api_1      |   --> POST /account/signin 200 139ms 193b
web_1      |   <-- GET /?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YWI1MDc5NTEzZTk1YzAwMmMyNTk4ODUiLCJpYXQiOjE1MjE4MTM5OTIsImF1ZCI6ImFwaSIsImlzcyI6ImFwaSJ9.vepmMHWOd2uQYagARxnLzIHVH1sBCImJqZ4obyglWxo
web_1      | error:  Error: connect ECONNREFUSED 127.0.0.1:3001
web_1      |     at Object._errnoException (util.js:1022:11)
web_1      |     at _exceptionWithHostPort (util.js:1044:20)
web_1      |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
web_1      |   --> GET /?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YWI1MDc5NTEzZTk1YzAwMmMyNTk4ODUiLCJpYXQiOjE1MjE4MTM5OTIsImF1ZCI6ImFwaSIsImlzcyI6ImFwaSJ9.vepmMHWOd2uQYagARxnLzIHVH1sBCImJqZ4obyglWxo 302 6ms 87b
api_1      |   <-- POST /account/signin
api_1      | error:  errors=[email=Email is required, email=Please enter a valid email address, password=Password is required, password=Incorrect email or password.]
api_1      |   --> POST /account/signin 400 2ms 169b
api_1      |   <-- POST /account/signin
api_1      |   --> POST /account/signin 200 132ms 193b
web_1      |   <-- GET /?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YWI1MDc5NTEzZTk1YzAwMmMyNTk4ODUiLCJpYXQiOjE1MjE4MTQwNzksImF1ZCI6ImFwaSIsImlzcyI6ImFwaSJ9.jKrZo3c3jBVytDfWps2hG8EdPqpyrfQLF4k-nhuG-Mc
web_1      | error:  Error: connect ECONNREFUSED 127.0.0.1:3001
web_1      |     at Object._errnoException (util.js:1022:11)
web_1      |     at _exceptionWithHostPort (util.js:1044:20)
web_1      |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
web_1      |   --> GET /?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YWI1MDc5NTEzZTk1YzAwMmMyNTk4ODUiLCJpYXQiOjE1MjE4MTQwNzksImF1ZCI6ImFwaSIsImlzcyI6ImFwaSJ9.jKrZo3c3jBVytDfWps2hG8EdPqpyrfQLF4k-nhuG-Mc 302 7ms 87b
```
@ezhivitsa
